### ISSUE TITLE
help file, randomForest/RandomForest

### ISSUE THREAD

**Issue by zmjones** [zmjones/edarf#23]
help apparently doesn't distinguish between the two, so only one shoes up (RandomForest).

**Comment by zmjones** [comment]
did we ever figure this out? it is still incorrect on my build

**Comment by flinder** [comment]
no, I looked around but found nobody else with the same problem. I'm gonna try again

**Comment by zmjones** [comment]
[google-fu to the rescue](https://stackoverflow.com/questions/7198758/roxygen2-how-to-properly-document-s3-methods)

**Comment by zmjones** [comment]
the docs are messed up now though, it repeated everything for each, so maybe we should document only the generic?
