### ISSUE TITLE
dependencies failed to install

### ISSUE THREAD

**Issue by flinder** [zmjones/edarf#37]
Just installed edarf on a new machine and the automatic installation of dependencies failed. Could however install the dependencies manually (specifically, in order: 'zoo', 'sandwich', 'strucchange' (Dependencies to party?)). 
Not a big deal but weird and not sure if systme specific

**Comment by zmjones** [comment]
Yes those are dependencies to party. Remember to use my forked copy if you want SE estimation.

I just restarted Travis to double check. I have some compiler breakage that is preventing me from double checking on my machine. Will update when I am sure.

I am actually going to rewrite a bit of in the next few days or so (using the much better code I wrote for mlr).

**Comment by flinder** [comment]
cool sounds good. Let me know if I can help

**Comment by zmjones** [comment]
yea it must be a local issue on your machine. Travis says the build runs cleanly from scratch. My first guess would be a compiler issue.
