### ISSUE TITLE
error with install from devtools

### ISSUE THREAD

**Issue by brooksandrew** [zmjones/edarf#39]
Hi there - read your [paper](http://zmjones.com/static/papers/rfss_manuscript.pdf).  Interesting stuff.  Would like to play around with your package, but I'm getting an install error on my mac using devtools.  Have you encountered this?

`devtools::install_github('zmjones/edarf')`

Downloading github repo zmjones/edarf@master
Installing edarf
Installing dependencies for edarf:
RcppArmadillo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 10 1239k   10  130k    0     0   168k      0  0:00:07 --:--:--  0:00:07  168k100 1239k  100 1239k    0     0  1356k      0 --:--:-- --:--:-- --:--:-- 1356k

The downloaded binary packages are in
	/var/folders/29/dj4wm1714q7flrdgvg7src8h0000gn/T//RtmpxEpsRy/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/29/dj4wm1714q7flrdgvg7src8h0000gn/T/RtmpxEpsRy/devtoolsa4220b25ed7/zmjones-edarf-e39a4c5'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

* installing *source* package ‘edarf’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/RcppArmadillo/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c edarf.cpp -o edarf.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/lib -o edarf.so RcppExports.o edarf.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edarf.so] Error 1
ERROR: compilation failed for package ‘edarf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/edarf’
Error: Command failed (1)

**Comment by zmjones** [comment]
No I haven't seen this one and wasn't able to replicate it. Compiler errors are no fun. Did Rcpp and RcppArmadillo install correctly and load w/o error?

You have Clang installed via Xcode I presume? Are you using the R binary? How is gfortran installed on your system? For reference I use the version of gfortran that is supplied in GCC which is installed (along with R) from source by homebrew. 

Since I am waiting on packages/forks not on CRAN I can't get them to generate a binary but if you know of a way that would be helpful.

**Comment by zmjones** [comment]
did you figure this out?

**Comment by brooksandrew** [comment]
sorry for delay. I'm not super familiar with the some of the software/installations you mentioned and haven't had to check on them pulling packages from GitHub before with devtools.

RcppAramadillo and Rcpp are load properly with `library()` in R.  Just reinstalled to most recent version to be sure

**clang specs:**
> Andrews-MacBook-Pro:~ ajb$ **clang --version**
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**R specs:**
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

Tried again today with `install_github('zmjones/edarf')`
Here are the warnings & error

> ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'  
ld: library not found for -lgfortran  
clang: error: linker command failed with exit code 1 (use -v to see invocation)  
make: *** [edarf.so] Error 1  
ERROR: compilation failed for package ‘edarf’  
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/edarf’  
Error: Command failed (1)

**Comment by zmjones** [comment]
So it looks like gfortran is not in the place that it is expected or is missing altogether. I know the build works fine on a clean linux system from scratch and it works on my Mac so I think this is particular to your system.

Are you using the R binary (i.e. R is installed using a `.dmg` file)? If so install [this](https://cran.r-project.org/bin/macosx/tools/gfortran-4.2.3.pkg). If you are using homebrew or another package manager you can install it [manually](http://stackoverflow.com/questions/23916219/os-x-package-installation-depends-on-gfortran-4-8).

Please let me know if that works.

**Comment by brooksandrew** [comment]
hmmm. yeah, R was installed from R-3.2.2.pkg.  Installed gfortran from your link.  No luck.  Same error, I l believe

> ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edarf.so] Error 1
ERROR: compilation failed for package ‘edarf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/edarf’
Error: Command failed (1)

**Comment by zmjones** [comment]
did you restart R after doing so?

if that doesn't work try manual installation.

```
curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
```

**Comment by brooksandrew** [comment]
manual install works.  thanks!  could this be bundled into the install, perhaps?

**Comment by zmjones** [comment]
No that is a system requirement. I think that would not pass R CMD check. This will be solved in a way though, when/if this eventually ends up on CRAN and there is a binary which doesn't require you to compile things. This is just an OSX specific thing that has to do with how the fortran compiler is packaged.

**Comment by zmjones** [comment]
Also if you plan on using more packages compiled from source I would recommend using [homebrew](http://brew.sh/). I have [a post](http://zmjones.com/mac-setup/) on doing all this on as well.

Hope the package works for you!
