### ISSUE TITLE
Examples in the help files

### ISSUE THREAD

**Issue by PhilippPro** [zmjones/edarf#47]
Some things I noticed while looking at the help files:

- extract_proximity has no example
- extract_prox does not exist, but is in your readme file?
- Why do you have ##not run in the plot_prox file?

**Comment by PhilippPro** [comment]
Moreover it maybe would be good to have links to other functions in the help file. (See also section). 

Some functions like e.g. `randomforest_dist` are not easy to find, maybe they could be linked somewhere. (or maybe you do not want to show them as they are "unsupported"?)

**Comment by zmjones** [comment]
Ok thanks. Yes I want `randomforest_dist` to be omitted. I might remove it entirely. I made all of the other changes you suggested.

I also restructured the repo so that there is a package folder which I'll submit to cran. cran requires me to have the license formatted the way i did before.

**Comment by zmjones** [comment]
feel free to close this if you think i satisfied all your requests here.

**Comment by PhilippPro** [comment]
The bad thing is, that you now cannot install it anymore with devtools via 

`devtools::install_github("zmjones/edarf")`

cause the package is in the folder.

**Comment by zmjones** [comment]
there is a subdir argument. i will say how to use this in the readme. `devtools::install_github("zmjones/edarf", subdir = "pkg")`. 

i don't think there is another way around that. cran requires i have the license setup differently.

**Comment by PhilippPro** [comment]
`devtools::install_github("zmjones/edarf/pkg")`

is also possible, this is not a big problem.
