### ISSUE TITLE
Reference in the joss paper above image

### ISSUE THREAD

**Issue by PhilippPro** [zmjones/edarf#49]
https://github.com/openjournals/joss-reviews/files/525302/10.21105.joss.00092.pdf

Moreover the joss paper is different to the paper in your github repo.

**Comment by zmjones** [comment]
i fixed the image location. it is hard to control it exactly with markdown to latex compiling.

what exactly was different. not the text as far as i can tell. they compiled it differently somehow. i looked around and didn't see any information about what they are doing though. i think as long as the text is fine this will be taken care of after it is published though. right?

**Comment by PhilippPro** [comment]
Maybe, I do not know. I also cannot compare anymore (I think author list was different e.g.), as you deleted the paper in the repo. ;)

**Comment by zmjones** [comment]
ah yes, well i just deleted the pdf version. i will re-add it.
