### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by PhilippPro** [zmjones/edarf#51]
You have two times `extract_proximity` in the readme. Moreover you have `randomforest_distance`, but the function is `randomforest_dist`. 
You do not mention ``randomforest_dist`` in the paper, but maybe this is not a problem. I really do not know what happens in `randomforest_dist`, you could add a reference or better explanation in the help.
Also references in the help of the other functions. 

Sorry for being very critical, but I think this could really improve the documentation.

**Comment by zmjones** [comment]
Ha no problem. Totally fair. Criticism is the point. Will fix this and the
other issue when I get to the office. Thanks again for reviewing this.

**Comment by zmjones** [comment]
I went ahead and removed it. I'll reimplement later if needed.

**Comment by PhilippPro** [comment]
- You still mention `extract_proximity` two times. 
- You do not have references in some of the help files (e.g. partial_dependence); If this is intended let me know. ;)

**Comment by zmjones** [comment]
do you mean references to articles? or links to the packages?

**Comment by zmjones** [comment]
ok did those things. thanks
