### ISSUE TITLE
Cite packages in the paper?

### ISSUE THREAD

**Issue by PhilippPro** [zmjones/edarf#52]
I am not completely sure about this, but maybe you should.

**Comment by zmjones** [comment]
Do you mean the rf packages? Or everything in imports? The former is
definitely a good idea. Golden rule and all.

**Comment by PhilippPro** [comment]
I though at least all packages that you mention in the paper.

**Comment by zmjones** [comment]
this is done. i used R's citation function, and cited the appropriate papers or the package directly as suggested.
