### ISSUE TITLE
Support for random forest fit by ranger

### ISSUE THREAD

**Issue by mikaelpoul** [zmjones/edarf#54]
First of all, your package is awesome! I merely have a friendly feature request.

The [ranger](https://github.com/imbs-hl/ranger) package, which you are probably familiar with, have huge speed improvements compared to randomForest and randomForestSRC. I often find the latter two to be too slow for large (or even medium-sized) data sets.

Do you have any plans to implement support for random forest fit by [ranger](https://github.com/imbs-hl/ranger), or do you know if anybody else is working on that?

**Comment by zmjones** [comment]
I didn't really have plans to add support for it here, but I just rewrote the package in such a way that doing this probably wouldn't be very hard. So maybe I will. Also basically all of this functionality has been implemented in [mlr](https://github.com/mlr-org/mlr) which supports ranger and a ton of other methods.

**Comment by mikaelpoul** [comment]
I understand! Sure, I tend to use [mlr](https://github.com/mlr-org/mlr) for this, but I often don't need the extended functionality, and the more standard approach with one rf function call + your pkg seems like a faster workflow for quick eda on new data. Your code looks pretty manageable, so I might just take a stab at myself, if OK :)

**Comment by zmjones** [comment]
No worries! I am almost done with it now. Will probably push the change
tonight

**Comment by mikaelpoul** [comment]
Awesome!

**Comment by zmjones** [comment]
just pushed the addition. let me know if there are problems.
